use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, BTreeSet};

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
#[serde(default, deny_unknown_fields)]
pub struct ProjectInput {
    pub stylesheets: Vec<StylesheetInput>,
    pub bindings: Vec<BindingInput>,
    pub complete_usage: bool,
    pub managed_classes: BTreeSet<String>,
    pub dynamic_classes: BTreeSet<String>,
    pub reserved_classes: BTreeSet<String>,
    pub reserved_prefixes: Vec<String>,
    /// Order within each loading group is significant. Rules never move across sheets.
    pub load_groups: Vec<Vec<String>>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct StylesheetInput {
    pub id: String,
    pub source: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
pub struct BindingInput {
    pub id: String,
    pub kind: BindingKind,
    pub value: String,
}

#[derive(Clone, Copy, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum BindingKind {
    Classes,
    Selector,
    Token,
    Html,
}

#[derive(Clone, Copy, Debug, Default, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum Mode {
    Baseline,
    Naming,
    #[default]
    Compact,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
#[serde(default, deny_unknown_fields)]
pub struct Options {
    pub mode: Mode,
    /// Upper bound on additional subset candidates per optimization round.
    pub search_limit: usize,
    /// Number of frequency-ranked identifiers considered for compression-aware swaps.
    pub name_swap_limit: usize,
    /// Measured structural candidates in the large-input search (tiny exact
    /// cases use their separately declared complete finite domain).
    pub max_evaluations: usize,
    pub max_rounds: usize,
}

impl Default for Options {
    fn default() -> Self {
        Self {
            mode: Mode::Compact,
            search_limit: 32,
            name_swap_limit: 8,
            max_evaluations: 2048,
            max_rounds: 32,
        }
    }
}

#[derive(Clone, Debug, Default, Deserialize, Serialize, PartialEq, Eq)]
pub struct EncodedSize {
    pub raw: usize,
    pub brotli: usize,
    pub gzip: usize,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct ArtifactSizes {
    pub css: EncodedSize,
    pub html: EncodedSize,
    pub javascript: EncodedSize,
    pub total: EncodedSize,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct TransformationReport {
    pub baseline: ArtifactSizes,
    pub naming: ArtifactSizes,
    pub optimized: ArtifactSizes,
    pub candidates_evaluated: usize,
    pub accepted_transformations: usize,
    pub shared_classes: usize,
    pub extracted_declarations: usize,
    pub elided_identities: usize,
    pub diagnostics: Vec<Diagnostic>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct Diagnostic {
    pub stylesheet: Option<String>,
    pub reason: String,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct Manifest {
    pub schema_version: u32,
    pub compiler_version: String,
    pub generation: String,
    pub identities: BTreeMap<String, String>,
    pub classes: BTreeMap<String, Vec<String>>,
    pub source_hashes: BTreeMap<String, String>,
    pub output_hashes: BTreeMap<String, String>,
    pub load_groups: Vec<Vec<String>>,
    /// Stable delivery chunk identities; rules remain in their original sheets.
    pub chunks: BTreeMap<String, Vec<String>>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct CompiledProject {
    pub stylesheets: BTreeMap<String, String>,
    pub bindings: BTreeMap<String, String>,
    pub manifest: Manifest,
    pub report: TransformationReport,
    /// CSS source maps generated by Lightning CSS, keyed by stylesheet identity.
    pub source_maps: BTreeMap<String, String>,
}

#[derive(Clone, Debug)]
pub struct PreparedProject {
    pub(crate) input: ProjectInput,
    pub(crate) compiled: CompiledProject,
    pub(crate) planned_sheets: BTreeMap<String, lightningcss::stylesheet::StyleSheet<'static>>,
}

impl PreparedProject {
    pub fn compiled(&self) -> &CompiledProject {
        &self.compiled
    }
    pub fn manifest(&self) -> &Manifest {
        &self.compiled.manifest
    }
    pub fn report(&self) -> &TransformationReport {
        &self.compiled.report
    }
}

#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("invalid project inventory: {0}")]
    Inventory(String),
    #[error("{stylesheet}: {message}")]
    Css { stylesheet: String, message: String },
    #[error("binding {binding}: {message}")]
    Binding { binding: String, message: String },
    #[error(transparent)]
    Io(#[from] std::io::Error),
    #[error(transparent)]
    Json(#[from] serde_json::Error),
}
